name: Docker Build Test

on:
  push:
    branches:
      -testWorkflowRun

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.set-tag.outputs.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build linux binary
        run: |
          mkdir -p build/binaries
          bun build ./src/cli.ts --compile --minify --sourcemap --target=bun --outfile ./build/binaries/linkinator-linux

      - name: Upload linux binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: linkinator-linux
          path: build/binaries/linkinator-linux

      - name: Set dummy tag name
        id: set-tag
        run: echo "tag_name=v1.0.0-test" >> $GITHUB_OUTPUT

  docker:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    env:
      DUMMY_TAG_NAME: ${{ needs.build.outputs.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download linux binary artifact
        uses: actions/download-artifact@v4
        with:
          name: linkinator-linux
          path: build/binaries



      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/linkinator
          tags: |
            type=semver,pattern={{version}},value=${{ env.DUMMY_TAG_NAME }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.DUMMY_TAG_NAME }}
            type=semver,pattern={{major}},value=${{ env.DUMMY_TAG_NAME }}
            type=raw,value=latest

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BINARY_PATH=build/binaries/linkinator-linux
